steps:
  # Download firebase secrets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: FIREBASE_CLIENT
    entrypoint: 'bash'
    args:
      [
        '-c',
        'gcloud secrets versions access latest --secret=firebase-client > firebase-config.js',
      ]
  # In case env variables are needed for the flask app.
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   id: ENV_VARS
  #   entrypoint: 'bash'
  #   args:
  #     [
  #       '-c',
  #       'gcloud secrets versions access latest --secret=makefile-env > Makefile-env',
  #     ]

  # Do `npm ci` to download and install FE dependencies
  - name: node:16-slim
    id: NPM_INSTALL
    entrypoint: bash
    args: ['-c', 'npm ci']

  # Do `npm run build` to build the FE files.
  - name: node:16-slim
    id: FE_BUILD
    waitFor:
      - NPM_INSTALL
      - FIREBASE_CLIENT
      # - ENV_VARS
    entrypoint: npm
    args: ['run', 'build']

  # Deploy app engine site.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: DEPLOY_GAE
    waitFor:
      - FE_BUILD
    entrypoint: 'bash'
    dir: '${_GAE}'
    args:
      [
        '-c',
        'gcloud app deploy --version=$(date +%F) --project=$PROJECT_ID --quiet --no-promote',
      ]

    # Deploy app engine site for QA to test before promote.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: DEPLOY_GAE_QA
    waitFor:
      - FE_BUILD
    entrypoint: 'bash'
    dir: '${_GAE}'
    args:
      [
        '-c',
        'gcloud app deploy --version=qa --project=$PROJECT_ID --quiet --no-promote',
      ]

  # Starts database with content.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: FIREBASE_DATABASE_UPDATE
    waitFor:
      - FE_BUILD
    entrypoint: 'bash'
    dir: 'cloud-functions/init-firebase'
    args: ['-c', 'pip3 install -r requirements.txt && python3 main.py']

  # Deploy dispatch yaml.
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   id: DEPLOY_GAE_DISPATCH
  #   waitFor:
  #     - DEPLOY_GAE
  #     - DEPLOY_GAE_QA
  #   entrypoint: 'bash'
  #   dir: '${_GAE}'
  #   args: ['-c', 'gcloud app deploy dispatch.yaml']

substitutions:
  _GAE: appengine
